# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', max_length=140),
        ),
    ]
