# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0002_auto_20160919_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('slug',)},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='slug',
        ),
    ]
