# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0002_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
